apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cilium
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/cilium
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-kyverno
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/kyverno
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: infra-cilium
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-longhorn
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/longhorn
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: infra-cilium
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cnpg
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/cnpg
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: infra-longhorn
    - name: infra-kyverno
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-keycloak
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/keycloak
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: infra-cnpg
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-platform-auth
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/platform-auth
  prune: true
  wait: true
  timeout: 5m

  dependsOn:
    - name: infra-cilium
    - name: infra-keycloak

  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-monitoring
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/monitoring
  prune: true
  wait: true
  timeout: 10m

  dependsOn:
    - name: infra-longhorn
    - name: infra-cilium
    - name: infra-platform-auth

  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-gateway-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/gateway-system
  prune: true
  wait: true
  timeout: 5m

  dependsOn:
    - name: infra-cilium
    - name: infra-keycloak
    - name: infra-platform-auth
    - name: infra-monitoring

  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-routes
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/routes
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: infra-gateway-system
  sourceRef:
    kind: GitRepository
    name: flux-system
